CREATE TABLE PROJECT (
    ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT PK_PROJECT PRIMARY KEY (ID)
);
COMMENT ON COLUMN PROJECT.ID IS '아이디(pk)';
COMMENT ON COLUMN PROJECT.NAME IS '프로젝트명';
COMMENT ON COLUMN PROJECT.USE_YN IS '(사용여부)';
